remote_theme: ELIXIR-Belgium/elixir-toolkit-theme
theme_variables:
  topnav:
    brand_logo: assets/img/everse_logo.png

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
