title: "RSQkit: Research Software Quality kit"
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: "RSQkit: Research Software Quality kit"
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "The Research Software Quality kit is a resource to help researchers that code, Research Software Engineers, and anyone in between learn about and apply best practices in creating research software and code."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.5.0

exclude:
  - README.md
  - Gemfile

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

theme_variables:
  topnav:
    brand_logo: assets/img/everse_logo.png
